linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo
    - dupl
    - gocritic
    - revive
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: if-return
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: "1.21"